### ISSUE TITLE
Possible False Corrections

### ISSUE THREAD

**Issue by christopherjenness** [sealneaward/shot-time#1]
First, this is really cool.  Thanks for putting this together.

It looks like your logic is:
- Find the highest z position the ball takes
- Trace back to find minimum velocity of ball before shot within 40 frames (1.6 sec)

That seems pretty straightforward, and accurate for almost every situation I can think of.  What about lobs though? It seems this method would assign the shot to the assister and not the dunker.  What do you think?

**Comment by sealneaward** [comment]
Hmm, you may be right in that the shot time would be attributed to the person throwing a lob and not the person getting the dunk. I'll see if I can do some kind of work around depending on the type of shot event in the event logs.

**Comment by christopherjenness** [comment]
I just thought of a work around, maybe.  Play-by-play data (or shot logs) says the distance.  (Player X made 11 ft, 2PT shot).  If you trust the distance in the play-by-play, you can use that.  For example, when did the ball leave the 11-foot radius from the hoop.

**Comment by sealneaward** [comment]
I was thinking of doing just that.

**Comment by sealneaward** [comment]
Fix has been added to fix_times to check for distance to recorded shot location in the 40 frame shot window.

https://github.com/sealneaward/shot-time/pull/2

**Comment by sealneaward** [comment]
I'll close this for now since it follows your suggestion, but I will open it in the future if new improvments can be made.
